title: Katrin Maliatski
description: Personal site built with the Minimal Jekyll theme.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed

# Ensure these are present
include:
  - assets/css
